spring:
  application:
    name: employee
server:
  port: 8093
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
